/**
 * promptQualityPipeline.js — Master Prompt Quality Assurance (PQA) Pipeline
 *
 * Dedicated video quality pipeline for video mode (mediaType === 'video').
 * Intercepts every generated prompt from PromptBuilder and executes:
 * Beat -> PromptBuilder -> Prompt Auditor -> Prompt Optimizer -> Prompt Validator -> Generation
 *
 * Enforces max 3 optimization iterations, score threshold >= 90, cross-beat repetition
 * detection, prompt diff generation, and structured logging per beat.
 */

import { auditPrompt } from "./promptAuditor.js";
import { optimizePrompt } from "./promptOptimizer.js";
import { validatePromptStructure } from "./promptQualityValidator.js";
import { PromptHistoryTracker } from "./promptHistoryTracker.js";
import { createLogger } from "../../../utils/logger.js";

const logger = createLogger("PromptQualityPipeline");

const MAX_OPTIMIZATION_ITERATIONS = 3;
const PASSING_SCORE_THRESHOLD = 90;

/**
 * Runs the complete Prompt Quality Assurance (PQA) pipeline over a set of state-based video prompts.
 *
 * @param {Array<object>} rawPrompts - List of prompt objects generated by PromptBuilder
 * @param {Array<object>} beats      - Atomic beats
 * @param {object} storyBible        - Story Bible
 * @param {object} options          - Pipeline options
 * @returns {Array<object>} Audited, optimized, and validated video prompt objects ready for Gemini Omni Flash
 */
export function runPromptQualityPipeline(rawPrompts = [], beats = [], storyBible = {}, options = {}) {
  logger.info(`🛡️ [PQA Pipeline] Starting Prompt Quality Assurance Pipeline over ${rawPrompts.length} video prompts...`);

  const historyTracker = new PromptHistoryTracker();
  const processedPrompts = [];

  for (let i = 0; i < rawPrompts.length; i++) {
    const rawPromptObj = rawPrompts[i];
    const nextBeat = beats[i + 1] || null;
    const historyContext = historyTracker.getHistoryContext(i, nextBeat);

    const result = processSinglePromptPqa(i + 1, rawPromptObj, historyContext);
    processedPrompts.push(result.finalPromptObj);

    // Record audited & optimized prompt into history tracker for downstream cross-beat checks
    historyTracker.recordBeat(i, result.finalPromptObj);
  }

  logger.info(`✅ [PQA Pipeline] Completed PQA processing for ${processedPrompts.length} video prompts.`);
  return processedPrompts;
}

/**
 * Executes the PQA loop for a single beat prompt (Audit -> Optimize -> Validate -> Score).
 *
 * @param {number} beatNumber
 * @param {object} initialPromptObj
 * @param {object} historyContext
 * @returns {{ finalPromptObj: object, auditLog: object }}
 */
export function processSinglePromptPqa(beatNumber, initialPromptObj, historyContext) {
  let currentPromptObj = { ...initialPromptObj };
  let iteration = 0;
  let finalReport = null;
  let validationResult = { valid: false, errors: [] };
  let approved = false;

  const initialLength = (currentPromptObj.prompt || "").length;
  let totalIssuesFoundCount = 0;

  while (iteration < MAX_OPTIMIZATION_ITERATIONS && !approved) {
    iteration++;

    // 1. Prompt Auditor (Phase 1 + Cross-Beat Repetition Detector)
    finalReport = auditPrompt(currentPromptObj, historyContext);
    if (iteration === 1) {
      totalIssuesFoundCount = finalReport.issues.length;
    }

    // 2. Check if score already meets threshold & structure is valid
    // Fix J-6: validationResult is now derived AFTER the audit (not before the loop),
    // so the first check uses real audit data instead of a pre-audit structural guess.
    validationResult = validatePromptStructure(currentPromptObj);

    const hasNoHardFailures = (finalReport.hardFailures || []).length === 0;

    if (finalReport.score >= PASSING_SCORE_THRESHOLD && validationResult.valid && hasNoHardFailures) {
      approved = true;
      break;
    }

    // 3. Prompt Optimizer (Phase 2 + Phase 6 Diff)
    logger.info(`🔧 [PQA Pipeline] Beat ${beatNumber}: Iteration ${iteration} optimization (Score: ${finalReport.score}, Issues: ${finalReport.issues.length}, Hard Failures: ${finalReport.hardFailures?.length || 0})...`);
    currentPromptObj = optimizePrompt(currentPromptObj, finalReport, historyContext);

    // 4. Prompt Validator (Phase 3)
    validationResult = validatePromptStructure(currentPromptObj);

    // Re-audit optimized prompt for updated score
    finalReport = auditPrompt(currentPromptObj, historyContext);
    const hasNoHardFailuresReaudit = (finalReport.hardFailures || []).length === 0;
    if (finalReport.score >= PASSING_SCORE_THRESHOLD && validationResult.valid && hasNoHardFailuresReaudit) {
      approved = true;
    }
  }

  const finalLength = (currentPromptObj.prompt || "").length;
  const issuesFixedCount = Math.max(0, totalIssuesFoundCount - finalReport.issues.length);

  // Attach PQA Audit Report and Metadata to Prompt Object
  currentPromptObj._pqaReport = {
    score: finalReport.score,
    categories: finalReport.categories,
    issues: finalReport.issues,
    approved,
    iterations: iteration,
    diff: currentPromptObj._pqaDiff || null,
  };

  // Phase 7 — Logging
  logger.info(`📊 [PQA Beat ${beatNumber}] ` +
    `Len: ${initialLength}→${finalLength} | ` +
    `Opts: ${iteration}/${MAX_OPTIMIZATION_ITERATIONS} | ` +
    `Issues Found: ${totalIssuesFoundCount} | ` +
    `Fixed: ${issuesFixedCount} | ` +
    `Final Score: ${finalReport.score}/100 | ` +
    `Approved: ${approved ? "YES" : "NO (Max Iterations)"}`);

  if (currentPromptObj._pqaDiff && currentPromptObj._pqaDiff.changes?.length > 0) {
    logger.info(`📝 [PQA Beat ${beatNumber} Diff] Changes: ${currentPromptObj._pqaDiff.changes.join(" | ")}`);
  }

  return {
    finalPromptObj: currentPromptObj,
    auditLog: {
      beatNumber,
      promptLengthBefore: initialLength,
      promptLengthAfter: finalLength,
      optimizationCount: iteration,
      issuesFound: totalIssuesFoundCount,
      issuesFixed: issuesFixedCount,
      finalScore: finalReport.score,
      generationApproved: approved,
    },
  };
}
